import { Geist, Geist_Mono } from "next/font/google";
import CustomLink from "./component/CustomLink";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <nav className=" p-4 border-b border-gray-400">
          <ul className="flex gap-x-2 items-center">
            <li><CustomLink path="/">home </CustomLink></li>

            <li>
              <CustomLink path="/settion">setting
              </CustomLink>

            </li>


          </ul>

        </nav>
        {children}
      </body>
    </html>
  );
}
